# Generated by Django 5.0.2 on 2024-02-08 16:09

import upload.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(db_index=True, storage=upload.storage.MinioStorage, upload_to=''),
        ),
    ]
